#!/usr/bin/env python3

import os
import amulet
import socket
from lib import assert_connect

d = amulet.Deployment(series='xenial')
d.add('tor-bridge', 'local:xenial/tor-bridge')

try:
    # Create the deployment described above, give us 900 seconds to do it
    d.setup(timeout=900)

    # Setup will only make sure the services are deployed, related, and in a
    # "started" state. We can employ the sentries to actually make sure there
    # are no more hooks being executed on any of the nodes.
    d.sentry.wait()
except amulet.helpers.TimeoutError:
    amulet.raise_status(amulet.SKIP, msg="Environment wasn't stood up in time")
except:
    # Something else has gone wrong, raise the error so we can see it and this
    # will automatically "FAIL" the test.
    raise

# Shorten the names a little to make working with unit data easier
tor_unit = d.sentry['tor-bridge'][0]

print("check for bridge listening on default port...", end='')
assert_connect(tor_unit.info['public-address'], 443)
print("OK")

print("check that changing the bridge port works...", end='')
d.configure('tor-bridge', {'port': 8443})
assert_connect(tor_unit.info['public-address'], 8443)
d.configure('tor-bridge', {'port': 443})
assert_connect(tor_unit.info['public-address'], 443)
print("OK")

